players-lands-enabled: true
guild-lands-enabled: true
#Allow creeper grief on players that are trusted for breaking blocs.
enable-creeper-grief: false

default-claim-limit: 5

guild-claim-prices:
  # Tranche 0 à 4
  0: 0
  # Tranche 5 à 10
  5: 1000

bluemap:
  enabled: true
  marker-set:
    label: "Territoires"
    default-hidden: false
  line-width: 2
  styles:
    player:
      line-color: "#3498DB"
      fill-color: "#3498DB"
      fill-opacity: 0.25
    guild:
      line-color: "#2ECC71"
      fill-color: "#2ECC71"
      fill-opacity: 0.25
    system:
      line-color: "#E74C3C"
      fill-color: "#E74C3C"
      fill-opacity: 0.25
